splash = false

wallpaper {
    monitor = desc:Ancor Communications Inc ROG PG279Q ##ASO/PRLo3X3d
    path = ~/.config/hypr/1.png
    fit_mode = cover
}

wallpaper {
    monitor = desc:Ancor Communications Inc VC279 F5LMRS035943
    path = ~/.config/hypr/2.png
    fit_mode = cover
}
